version: "3.8"

services:
  db:
    image: postgres
    container_name: sound-ai-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: noob
      POSTGRES_PASSWORD: noob
      POSTGRES_DB: noob
  web:
    image: web
    build: ../backend
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./web-data:/app/data
    environment:
      - DATABASE_URL=postgres://noob:noob@sound-ai-database/noob
      - "JWT_SECRET_KEY=${JWT_SECRET_KEY:-shernoob}"
